// @vitest-environment jsdom
// Phonetics data source (fork issue #5), tested at the fetchProxy seam.
// IPA comes from a dictionary API, never generated by the LLM (hallucination
// risk on rare words); lookups are gated by a privacy setting.
import { describe, test, expect, beforeEach, vi } from 'vitest';
import browser from './browser-polyfill';
import { isEnglishWord, lookupPhonetics, clearPhoneticsCache } from './dictionary';
import { generalSettings } from './storage-utils';

// Trimmed dictionaryapi.dev payload shape
const BANK_ENTRY = [{
	word: 'bank',
	phonetics: [
		{ text: '/bæŋk/', audio: 'https://api.dictionaryapi.dev/media/pronunciations/en/bank-uk.mp3' },
		{ text: '/bæŋk/', audio: 'https://api.dictionaryapi.dev/media/pronunciations/en/bank-us.mp3' }
	]
}];

describe('isEnglishWord', () => {
	test('accepts plain and hyphenated/apostrophe words', () => {
		expect(isEnglishWord('bank')).toBe(true);
		expect(isEnglishWord("don't")).toBe(true);
		expect(isEnglishWord('well-known')).toBe(true);
	});

	test('rejects CJK, numbers and multi-word strings', () => {
		expect(isEnglishWord('银行')).toBe(false);
		expect(isEnglishWord('42')).toBe(false);
		expect(isEnglishWord('interest rates')).toBe(false);
	});
});

describe('lookupPhonetics', () => {
	const sendMessage = vi.spyOn(browser.runtime, 'sendMessage');

	beforeEach(() => {
		sendMessage.mockReset();
		clearPhoneticsCache();
		generalSettings.readerSettings = {
			...generalSettings.readerSettings,
			dictionaryLookupEnabled: true
		};
	});

	function dictionaryAnswers(entriesByWord: Record<string, unknown>) {
		sendMessage.mockImplementation(async (message: any) => {
			const url = String(message.url);
			const word = decodeURIComponent(url.split('/').pop() || '');
			const entry = entriesByWord[word];
			if (entry) {
				return { ok: true, status: 200, text: JSON.stringify(entry) };
			}
			return { ok: false, status: 404, text: '{"title":"No Definitions Found"}' };
		});
	}

	test('maps UK and US IPA with audio URLs', async () => {
		dictionaryAnswers({ bank: BANK_ENTRY });

		const result = await lookupPhonetics('bank');

		expect(result).toEqual({
			uk: { ipa: '/bæŋk/', audioUrl: 'https://api.dictionaryapi.dev/media/pronunciations/en/bank-uk.mp3' },
			us: { ipa: '/bæŋk/', audioUrl: 'https://api.dictionaryapi.dev/media/pronunciations/en/bank-us.mp3' }
		});
		const url = String((sendMessage.mock.calls[0][0] as any).url);
		expect(url).toContain('/bank');
	});

	test('strips surrounding punctuation and lowercases before querying', async () => {
		dictionaryAnswers({ bank: BANK_ENTRY });

		const result = await lookupPhonetics('"Bank,"');

		expect(result).not.toBeNull();
	});

	test('falls back through the normalization chain: running → run', async () => {
		dictionaryAnswers({
			run: [{ word: 'run', phonetics: [{ text: '/rʌn/', audio: '' }] }]
		});

		const result = await lookupPhonetics('running');

		expect(result?.uk?.ipa || result?.us?.ipa).toBe('/rʌn/');
		// It tried the raw form first, then reduced forms until the hit
		const tried = sendMessage.mock.calls.map(c => String((c[0] as any).url).split('/').pop());
		expect(tried[0]).toBe('running');
		expect(tried).toContain('run');
	});

	test('returns null when every candidate misses', async () => {
		dictionaryAnswers({});

		const result = await lookupPhonetics('zzzz');

		expect(result).toBeNull();
	});

	test('caches by normalized form — repeated lookups make no new requests', async () => {
		dictionaryAnswers({ bank: BANK_ENTRY });

		await lookupPhonetics('bank');
		const calls = sendMessage.mock.calls.length;
		await lookupPhonetics('Bank');
		await lookupPhonetics('bank,');

		expect(sendMessage.mock.calls.length).toBe(calls);
	});

	test('privacy switch off: resolves null without any network request', async () => {
		generalSettings.readerSettings = {
			...generalSettings.readerSettings,
			dictionaryLookupEnabled: false
		};
		dictionaryAnswers({ bank: BANK_ENTRY });

		const result = await lookupPhonetics('bank');

		expect(result).toBeNull();
		expect(sendMessage).not.toHaveBeenCalled();
	});

	test('non-English input resolves null without any network request', async () => {
		dictionaryAnswers({});

		const result = await lookupPhonetics('银行');

		expect(result).toBeNull();
		expect(sendMessage).not.toHaveBeenCalled();
	});

	test('a custom dictionary base URL is honored', async () => {
		generalSettings.readerSettings = {
			...generalSettings.readerSettings,
			dictionaryBaseUrl: 'http://127.0.0.1:8123/entries/'
		};
		dictionaryAnswers({ bank: BANK_ENTRY });

		await lookupPhonetics('bank');

		const url = String((sendMessage.mock.calls[0][0] as any).url);
		expect(url).toBe('http://127.0.0.1:8123/entries/bank');
	});
});
